spring:
  datasource:
    username: security_user #username from docker-compose
    password: secret #password from docker-compose
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres

  liquibase:
    change-log: db/db.changelog-master.yml

  data:
    redis:
      host: localhost
      port: 6379

  session:
    timeout: 1d

  mail:
    host: smtp.gmail.com
    port: 587
    username: #your Gmail
    password: #your Google app password
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true